import { NextResponse } from "next/server";
import { Opportunity } from "@/types/database";

// Curated real opportunities from top companies
const curatedOpportunities: Opportunity[] = [
  {
    id: "google-swe-intern-2025",
    title: "Software Engineering Intern, Summer 2025",
    company: "Google",
    location: "Mountain View, CA",
    description: "Build next-generation technologies that change how billions of users connect, explore, and interact. Join our team and work on projects that matter.",
    salary_min: 8500,
    salary_max: 10000,
    url: "https://www.google.com/about/careers/applications/jobs/results/?q=intern",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 95,
    tags: ["Python", "Java", "Machine Learning", "Cloud"],
    source: "direct",
  },
  {
    id: "meta-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Meta",
    location: "Menlo Park, CA",
    description: "Help build products that bring people together. Work on large-scale systems that serve billions of users worldwide.",
    salary_min: 8000,
    salary_max: 10000,
    url: "https://www.metacareers.com/jobs?roles[0]=intern",
    posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 93,
    tags: ["React", "Python", "Mobile", "AI"],
    source: "direct",
  },
  {
    id: "apple-swe-intern-2025",
    title: "Software Engineering Internship",
    company: "Apple",
    location: "Cupertino, CA",
    description: "Create products that empower people and enrich their lives. Join the team that builds the world's most innovative technology.",
    salary_min: 7500,
    salary_max: 9500,
    url: "https://jobs.apple.com/en-us/search?team=internships-STDNT-INTRN",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 91,
    tags: ["Swift", "iOS", "Machine Learning", "Hardware"],
    source: "direct",
  },
  {
    id: "netflix-swe-intern-2025",
    title: "Software Engineer Intern - Summer 2025",
    company: "Netflix",
    location: "Los Gatos, CA",
    description: "Join the team that entertains the world. Work on streaming technology, recommendation systems, and content delivery.",
    salary_min: 9000,
    salary_max: 11000,
    url: "https://jobs.netflix.com/search?q=intern",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 89,
    tags: ["Java", "Python", "AWS", "Data"],
    source: "direct",
  },
  {
    id: "amazon-sde-intern-2025",
    title: "SDE Intern - Summer 2025",
    company: "Amazon",
    location: "San Francisco, CA",
    description: "Invent and simplify. Build systems that power the world's largest e-commerce platform and cloud infrastructure.",
    salary_min: 8000,
    salary_max: 9500,
    url: "https://www.amazon.jobs/en/teams/internships-for-students",
    posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 92,
    tags: ["Java", "AWS", "Python", "Distributed Systems"],
    source: "direct",
  },
  {
    id: "microsoft-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Microsoft",
    location: "San Francisco, CA",
    description: "Empower every person and organization on the planet to achieve more. Work on Azure, Office, Windows, and more.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://careers.microsoft.com/students/us/en/usuniversityinternship",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 90,
    tags: ["C#", "Azure", "TypeScript", "AI"],
    source: "direct",
  },
  {
    id: "stripe-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Stripe",
    location: "San Francisco, CA",
    description: "Help increase the GDP of the internet. Build the financial infrastructure that powers millions of businesses.",
    salary_min: 8500,
    salary_max: 10500,
    url: "https://stripe.com/jobs/search?teams=Interns",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 88,
    tags: ["Ruby", "JavaScript", "APIs", "Payments"],
    source: "direct",
  },
  {
    id: "salesforce-intern-2025",
    title: "Software Engineer Intern - Summer 2025",
    company: "Salesforce",
    location: "San Francisco, CA",
    description: "Join the #1 CRM company. Build cloud-based software that helps businesses connect with their customers.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://salesforce.wd12.myworkdayjobs.com/en-US/Futureforce_Internships",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 85,
    tags: ["Java", "Apex", "Cloud", "CRM"],
    source: "direct",
  },
  {
    id: "uber-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Uber",
    location: "San Francisco, CA",
    description: "Reimagine the way the world moves. Work on marketplace algorithms, maps, and real-time systems.",
    salary_min: 8000,
    salary_max: 9500,
    url: "https://www.uber.com/us/en/careers/teams/university/",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 87,
    tags: ["Python", "Go", "Machine Learning", "Mobile"],
    source: "direct",
  },
  {
    id: "airbnb-swe-intern-2025",
    title: "Software Engineer Intern - Summer 2025",
    company: "Airbnb",
    location: "San Francisco, CA",
    description: "Create a world where anyone can belong anywhere. Build the platform that connects millions of hosts and travelers.",
    salary_min: 8500,
    salary_max: 10000,
    url: "https://careers.airbnb.com/university/",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 86,
    tags: ["React", "Ruby", "Data", "Mobile"],
    source: "direct",
  },
  {
    id: "linkedin-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "LinkedIn",
    location: "Sunnyvale, CA",
    description: "Connect the world's professionals. Work on the platform that helps 900M+ members find opportunities.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://careers.linkedin.com/students",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 88,
    tags: ["Java", "Scala", "AI", "Data"],
    source: "direct",
  },
  {
    id: "nvidia-swe-intern-2025",
    title: "Software Engineering Intern - AI/ML",
    company: "NVIDIA",
    location: "Santa Clara, CA",
    description: "Shape the future of AI computing. Work on GPU technology that powers the AI revolution.",
    salary_min: 8000,
    salary_max: 10000,
    url: "https://nvidia.wd5.myworkdayjobs.com/UniversityJobs",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 91,
    tags: ["CUDA", "Python", "C++", "Deep Learning"],
    source: "direct",
  },
  {
    id: "adobe-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Adobe",
    location: "San Jose, CA",
    description: "Create the future of digital experiences. Build creative tools used by millions worldwide.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://adobe.wd5.myworkdayjobs.com/en-US/external_university",
    posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 84,
    tags: ["JavaScript", "C++", "AI", "Design"],
    source: "direct",
  },
  {
    id: "slack-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Slack (Salesforce)",
    location: "San Francisco, CA",
    description: "Make work life simpler, more pleasant, and more productive. Build the platform teams love.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://slack.com/careers/university-recruiting",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 83,
    tags: ["TypeScript", "React", "Electron", "APIs"],
    source: "direct",
  },
  {
    id: "coinbase-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Coinbase",
    location: "San Francisco, CA",
    description: "Build the future of finance. Create an open financial system for the world using blockchain technology.",
    salary_min: 8500,
    salary_max: 10500,
    url: "https://www.coinbase.com/careers/university",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 86,
    tags: ["Go", "React", "Blockchain", "Security"],
    source: "direct",
  },
  {
    id: "doordash-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "DoorDash",
    location: "San Francisco, CA",
    description: "Empower local economies. Build the logistics platform that connects customers, merchants, and dashers.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://careers.doordash.com/students",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 82,
    tags: ["Kotlin", "Python", "Machine Learning", "iOS"],
    source: "direct",
  },
  {
    id: "robinhood-swe-intern-2025",
    title: "Software Engineer Intern - Summer 2025",
    company: "Robinhood",
    location: "Menlo Park, CA",
    description: "Democratize finance for all. Build the platform that makes investing accessible to everyone.",
    salary_min: 8000,
    salary_max: 9500,
    url: "https://robinhood.com/us/en/careers/",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 85,
    tags: ["Python", "Go", "React", "Fintech"],
    source: "direct",
  },
  {
    id: "pinterest-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Pinterest",
    location: "San Francisco, CA",
    description: "Bring everyone the inspiration to create a life they love. Build visual discovery at scale.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://www.pinterestcareers.com/early-career/",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 81,
    tags: ["Python", "Java", "Machine Learning", "Computer Vision"],
    source: "direct",
  },
  {
    id: "figma-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Figma",
    location: "San Francisco, CA",
    description: "Make design accessible to all. Build the collaborative interface design tool loved by millions.",
    salary_min: 8000,
    salary_max: 10000,
    url: "https://www.figma.com/careers/",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 89,
    tags: ["TypeScript", "React", "WebGL", "C++"],
    source: "direct",
  },
  {
    id: "discord-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Discord",
    location: "San Francisco, CA",
    description: "Create space for everyone to find belonging. Build the platform where communities come together.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://discord.com/careers",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 87,
    tags: ["Rust", "Python", "React", "Elixir"],
    source: "direct",
  },
  // Data Science / ML Internships
  {
    id: "openai-ml-intern-2025",
    title: "Research Intern - Machine Learning",
    company: "OpenAI",
    location: "San Francisco, CA",
    description: "Ensure AGI benefits all of humanity. Work on cutting-edge AI research and development.",
    salary_min: 10000,
    salary_max: 14000,
    url: "https://openai.com/careers/",
    posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Research",
    opportunity_type: "internship",
    match_score: 94,
    tags: ["Python", "PyTorch", "Transformers", "Research"],
    source: "direct",
  },
  {
    id: "anthropic-ml-intern-2025",
    title: "Research Scientist Intern",
    company: "Anthropic",
    location: "San Francisco, CA",
    description: "Build reliable, interpretable, and steerable AI systems. Research the frontier of AI safety.",
    salary_min: 10000,
    salary_max: 13000,
    url: "https://www.anthropic.com/careers",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Research",
    opportunity_type: "internship",
    match_score: 93,
    tags: ["Python", "Machine Learning", "AI Safety", "Research"],
    source: "direct",
  },
  // Product / Design Internships
  {
    id: "spotify-pm-intern-2025",
    title: "Product Manager Intern",
    company: "Spotify",
    location: "Los Angeles, CA",
    description: "Unlock the potential of human creativity. Help shape the future of audio streaming.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://www.lifeatspotify.com/students",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Product",
    opportunity_type: "internship",
    match_score: 80,
    tags: ["Product", "Strategy", "Data Analysis", "UX"],
    source: "direct",
  },
  {
    id: "google-pm-intern-2025",
    title: "Associate Product Manager Intern",
    company: "Google",
    location: "Mountain View, CA",
    description: "Lead product development for products used by billions. The APM program launches careers in product.",
    salary_min: 8500,
    salary_max: 10000,
    url: "https://www.google.com/about/careers/applications/jobs/results/?q=APM%20intern",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Product",
    opportunity_type: "internship",
    match_score: 88,
    tags: ["Product", "Strategy", "Technical", "Leadership"],
    source: "direct",
  },
  // Entry Level Jobs
  {
    id: "google-l3-2025",
    title: "Software Engineer, New Grad (L3)",
    company: "Google",
    location: "Mountain View, CA",
    description: "Start your career at Google. Build products that impact billions of users.",
    salary_min: 150000,
    salary_max: 180000,
    url: "https://www.google.com/about/careers/applications/jobs/results/?q=new%20grad",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "job",
    match_score: 90,
    tags: ["Python", "Java", "Distributed Systems", "Algorithms"],
    source: "direct",
  },
  {
    id: "meta-e3-2025",
    title: "Software Engineer, New Grad (E3)",
    company: "Meta",
    location: "Menlo Park, CA",
    description: "Build the future of social connection. Join our engineering team as a new grad.",
    salary_min: 145000,
    salary_max: 175000,
    url: "https://www.metacareers.com/jobs?roles[0]=full-time",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "job",
    match_score: 89,
    tags: ["React", "Python", "Mobile", "AI"],
    source: "direct",
  },
  {
    id: "apple-ict-2025",
    title: "Software Engineer - New Grad",
    company: "Apple",
    location: "Cupertino, CA",
    description: "Join Apple's engineering team. Work on products that millions of people use every day.",
    salary_min: 140000,
    salary_max: 170000,
    url: "https://jobs.apple.com/en-us/search?team=apps-and-frameworks-SFTWR-AF",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "job",
    match_score: 87,
    tags: ["Swift", "Objective-C", "iOS", "macOS"],
    source: "direct",
  },
  {
    id: "stripe-new-grad-2025",
    title: "New Grad Software Engineer",
    company: "Stripe",
    location: "San Francisco, CA",
    description: "Increase the GDP of the internet. Build financial infrastructure at scale.",
    salary_min: 155000,
    salary_max: 185000,
    url: "https://stripe.com/jobs/search?teams=New%20Grad",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "job",
    match_score: 88,
    tags: ["Ruby", "Go", "APIs", "Distributed Systems"],
    source: "direct",
  },
  // Los Angeles Companies
  {
    id: "spacex-swe-intern-2025",
    title: "Software Engineering Intern - Summer 2025",
    company: "SpaceX",
    location: "Hawthorne, CA",
    description: "Join the team making humanity multiplanetary. Work on flight software, ground systems, and more.",
    salary_min: 7500,
    salary_max: 9500,
    url: "https://www.spacex.com/careers/",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 94,
    tags: ["C++", "Python", "Embedded", "Linux"],
    source: "direct",
  },
  {
    id: "disney-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "The Walt Disney Company",
    location: "Burbank, CA",
    description: "Create magic through technology. Work on streaming, parks technology, and entertainment platforms.",
    salary_min: 6500,
    salary_max: 8000,
    url: "https://jobs.disneycareers.com/search-jobs?k=intern",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 85,
    tags: ["Java", "AWS", "React", "Mobile"],
    source: "direct",
  },
  {
    id: "snapchat-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Snap Inc.",
    location: "Los Angeles, CA",
    description: "Build products that empower people to express themselves. Work on Snapchat, AR, and more.",
    salary_min: 8000,
    salary_max: 10000,
    url: "https://careers.snap.com/university",
    posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 90,
    tags: ["iOS", "Android", "AR", "Machine Learning"],
    source: "direct",
  },
  {
    id: "riot-games-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Riot Games",
    location: "Los Angeles, CA",
    description: "Build games that millions of players love. Join the team behind League of Legends and Valorant.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://www.riotgames.com/en/university-programs",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 88,
    tags: ["C++", "Game Dev", "Backend", "Cloud"],
    source: "direct",
  },
  {
    id: "hulu-swe-intern-2025",
    title: "Software Development Intern",
    company: "Hulu",
    location: "Santa Monica, CA",
    description: "Shape the future of streaming. Build technology that delivers entertainment to millions.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://www.hulu.com/jobs",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 84,
    tags: ["Python", "AWS", "Video", "React"],
    source: "direct",
  },
  {
    id: "activision-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Activision Blizzard",
    location: "Santa Monica, CA",
    description: "Work on games played by millions. Join the team behind Call of Duty, World of Warcraft, and more.",
    salary_min: 6500,
    salary_max: 8000,
    url: "https://careers.activisionblizzard.com/",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 86,
    tags: ["C++", "Game Dev", "Graphics", "Networking"],
    source: "direct",
  },
  {
    id: "tiktok-la-swe-intern-2025",
    title: "Software Engineer Intern - LA",
    company: "TikTok",
    location: "Los Angeles, CA",
    description: "Inspire creativity and bring joy. Build the platform that's reshaping entertainment.",
    salary_min: 8000,
    salary_max: 10000,
    url: "https://careers.tiktok.com/position?keywords=intern",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 91,
    tags: ["Python", "Go", "Machine Learning", "Video"],
    source: "direct",
  },
  // San Diego Companies
  {
    id: "qualcomm-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Qualcomm",
    location: "San Diego, CA",
    description: "Invent breakthrough technologies that transform how the world connects, computes, and communicates.",
    salary_min: 7000,
    salary_max: 9000,
    url: "https://qualcomm.wd5.myworkdayjobs.com/External/",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 87,
    tags: ["C++", "Embedded", "5G", "Machine Learning"],
    source: "direct",
  },
  {
    id: "intuit-sd-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Intuit",
    location: "San Diego, CA",
    description: "Power prosperity around the world. Build products like TurboTax, QuickBooks, and Mint.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://jobs.intuit.com/category/intern-jobs/27595/9702/1",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 85,
    tags: ["Java", "React", "AWS", "Fintech"],
    source: "direct",
  },
  {
    id: "illumina-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Illumina",
    location: "San Diego, CA",
    description: "Unlock the power of the genome. Build software that advances genomics and healthcare.",
    salary_min: 6500,
    salary_max: 8000,
    url: "https://www.illumina.com/company/careers.html",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 82,
    tags: ["Python", "Bioinformatics", "Cloud", "Data"],
    source: "direct",
  },
  {
    id: "servicenow-sd-intern-2025",
    title: "Software Engineering Intern",
    company: "ServiceNow",
    location: "San Diego, CA",
    description: "Make the world of work, work better for people. Build enterprise workflow automation.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://careers.servicenow.com/careers/jobs?keywords=intern",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 83,
    tags: ["JavaScript", "Java", "Cloud", "AI"],
    source: "direct",
  },
  // Orange County
  {
    id: "blizzard-swe-intern-2025",
    title: "Game Software Engineering Intern",
    company: "Blizzard Entertainment",
    location: "Irvine, CA",
    description: "Create epic entertainment experiences. Work on legendary games like Overwatch and Diablo.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://careers.blizzard.com/global/en/students-recent-grads",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 89,
    tags: ["C++", "Game Dev", "3D Graphics", "Networking"],
    source: "direct",
  },
  {
    id: "western-digital-intern-2025",
    title: "Software Engineering Intern",
    company: "Western Digital",
    location: "Irvine, CA",
    description: "Unleash the potential of data. Build storage solutions that power the digital world.",
    salary_min: 6500,
    salary_max: 8000,
    url: "https://jobs.westerndigital.com/",
    posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 79,
    tags: ["C", "Firmware", "Storage", "Linux"],
    source: "direct",
  },
  {
    id: "broadcom-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Broadcom",
    location: "Irvine, CA",
    description: "Connect everything. Build semiconductor and infrastructure software solutions.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://www.broadcom.com/company/careers",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 80,
    tags: ["C++", "Networking", "Embedded", "Linux"],
    source: "direct",
  },
  // More Bay Area startups
  {
    id: "dropbox-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Dropbox",
    location: "San Francisco, CA",
    description: "Design a more enlightened way of working. Build cloud storage and collaboration tools.",
    salary_min: 8000,
    salary_max: 9500,
    url: "https://www.dropbox.com/jobs/university",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 86,
    tags: ["Python", "Go", "Rust", "Distributed Systems"],
    source: "direct",
  },
  {
    id: "twitch-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Twitch",
    location: "San Francisco, CA",
    description: "Build the future of live entertainment. Create tools for millions of creators and viewers.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://www.twitch.tv/jobs/careers/university/",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 87,
    tags: ["Go", "React", "Video", "AWS"],
    source: "direct",
  },
  {
    id: "instacart-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Instacart",
    location: "San Francisco, CA",
    description: "Build the future of grocery. Create technology that serves millions of customers.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://instacart.careers/university/",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 84,
    tags: ["Ruby", "Python", "Machine Learning", "Mobile"],
    source: "direct",
  },
  {
    id: "plaid-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Plaid",
    location: "San Francisco, CA",
    description: "Unlock financial freedom for everyone. Build the infrastructure for fintech.",
    salary_min: 8500,
    salary_max: 10000,
    url: "https://plaid.com/careers/",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 88,
    tags: ["Go", "TypeScript", "Fintech", "APIs"],
    source: "direct",
  },
  {
    id: "notion-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Notion",
    location: "San Francisco, CA",
    description: "Make toolmaking ubiquitous. Build the all-in-one workspace for teams.",
    salary_min: 8000,
    salary_max: 10000,
    url: "https://www.notion.so/careers",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 91,
    tags: ["TypeScript", "React", "Kotlin", "Swift"],
    source: "direct",
  },
  {
    id: "databricks-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Databricks",
    location: "San Francisco, CA",
    description: "Help data teams solve the world's toughest problems. Build the data and AI company.",
    salary_min: 9000,
    salary_max: 11000,
    url: "https://www.databricks.com/company/careers/university-recruiting",
    posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 92,
    tags: ["Scala", "Python", "Spark", "Machine Learning"],
    source: "direct",
  },
  {
    id: "snowflake-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Snowflake",
    location: "San Mateo, CA",
    description: "Mobilize the world's data. Build the data cloud platform used by thousands of companies.",
    salary_min: 8500,
    salary_max: 10500,
    url: "https://careers.snowflake.com/us/en/university",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 89,
    tags: ["Java", "C++", "Cloud", "Data"],
    source: "direct",
  },
  {
    id: "scale-ai-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Scale AI",
    location: "San Francisco, CA",
    description: "Accelerate the development of AI applications. Build data infrastructure for machine learning.",
    salary_min: 9000,
    salary_max: 11000,
    url: "https://scale.com/careers",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 90,
    tags: ["Python", "TypeScript", "Machine Learning", "Data"],
    source: "direct",
  },
  {
    id: "ramp-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Ramp",
    location: "San Francisco, CA",
    description: "Help companies spend less. Build corporate cards and expense management platform.",
    salary_min: 8500,
    salary_max: 10500,
    url: "https://ramp.com/careers",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 87,
    tags: ["Python", "TypeScript", "Fintech", "React"],
    source: "direct",
  },
  {
    id: "rippling-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Rippling",
    location: "San Francisco, CA",
    description: "Magically simplify IT, HR, and Finance. Build the platform that runs companies.",
    salary_min: 8000,
    salary_max: 10000,
    url: "https://www.rippling.com/careers",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 86,
    tags: ["Python", "React", "Django", "AWS"],
    source: "direct",
  },
  {
    id: "airtable-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Airtable",
    location: "San Francisco, CA",
    description: "Democratize software creation. Build the no-code platform for modern teams.",
    salary_min: 8000,
    salary_max: 9500,
    url: "https://airtable.com/careers",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 85,
    tags: ["TypeScript", "React", "Node.js", "PostgreSQL"],
    source: "direct",
  },
  {
    id: "retool-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Retool",
    location: "San Francisco, CA",
    description: "Change how software is built. Help teams build internal tools faster.",
    salary_min: 8500,
    salary_max: 10000,
    url: "https://retool.com/careers",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 88,
    tags: ["TypeScript", "React", "PostgreSQL", "Docker"],
    source: "direct",
  },
  {
    id: "brex-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Brex",
    location: "San Francisco, CA",
    description: "Reimagine financial systems. Build the AI-powered spend platform for growing companies.",
    salary_min: 8500,
    salary_max: 10500,
    url: "https://www.brex.com/careers",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 87,
    tags: ["Kotlin", "TypeScript", "Fintech", "AWS"],
    source: "direct",
  },
  {
    id: "chime-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Chime",
    location: "San Francisco, CA",
    description: "Make money easy. Build the banking platform that helps millions manage their finances.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://www.chime.com/careers/",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 84,
    tags: ["Python", "Kotlin", "Fintech", "Mobile"],
    source: "direct",
  },
  // Marketing / Business Internships
  {
    id: "google-marketing-intern-2025",
    title: "Marketing Intern - Summer 2025",
    company: "Google",
    location: "Mountain View, CA",
    description: "Shape how Google products reach users. Work on brand, growth, and product marketing.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://www.google.com/about/careers/applications/jobs/results/?q=marketing%20intern",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Marketing",
    opportunity_type: "internship",
    match_score: 82,
    tags: ["Marketing", "Analytics", "Brand", "Strategy"],
    source: "direct",
  },
  {
    id: "meta-marketing-intern-2025",
    title: "Marketing Science Intern",
    company: "Meta",
    location: "Menlo Park, CA",
    description: "Use data to power marketing decisions. Work with advertisers and internal teams.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://www.metacareers.com/jobs?roles[0]=intern",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Marketing",
    opportunity_type: "internship",
    match_score: 81,
    tags: ["Data Analysis", "Marketing", "SQL", "Python"],
    source: "direct",
  },
  {
    id: "salesforce-marketing-intern-2025",
    title: "Marketing Intern - Futureforce",
    company: "Salesforce",
    location: "San Francisco, CA",
    description: "Drive marketing initiatives for the world's #1 CRM company.",
    salary_min: 6500,
    salary_max: 8000,
    url: "https://salesforce.wd12.myworkdayjobs.com/en-US/Futureforce_Internships",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Marketing",
    opportunity_type: "internship",
    match_score: 78,
    tags: ["Marketing", "Content", "Digital", "Analytics"],
    source: "direct",
  },
  // Data Science / Analytics Internships
  {
    id: "netflix-data-intern-2025",
    title: "Data Science Intern",
    company: "Netflix",
    location: "Los Gatos, CA",
    description: "Use data to shape content and personalization. Work on recommendation systems and analytics.",
    salary_min: 9000,
    salary_max: 11000,
    url: "https://jobs.netflix.com/search?q=intern",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Data Science",
    opportunity_type: "internship",
    match_score: 90,
    tags: ["Python", "SQL", "Machine Learning", "Statistics"],
    source: "direct",
  },
  {
    id: "uber-data-intern-2025",
    title: "Data Scientist Intern",
    company: "Uber",
    location: "San Francisco, CA",
    description: "Use data to optimize marketplace dynamics. Work on pricing, matching, and forecasting.",
    salary_min: 8000,
    salary_max: 10000,
    url: "https://www.uber.com/us/en/careers/teams/university/",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Data Science",
    opportunity_type: "internship",
    match_score: 88,
    tags: ["Python", "SQL", "Machine Learning", "Statistics"],
    source: "direct",
  },
  {
    id: "airbnb-data-intern-2025",
    title: "Data Science Intern",
    company: "Airbnb",
    location: "San Francisco, CA",
    description: "Use data to help people belong anywhere. Work on search, pricing, and trust & safety.",
    salary_min: 8500,
    salary_max: 10000,
    url: "https://careers.airbnb.com/university/",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Data Science",
    opportunity_type: "internship",
    match_score: 87,
    tags: ["Python", "SQL", "A/B Testing", "Statistics"],
    source: "direct",
  },
  // Design Internships
  {
    id: "apple-design-intern-2025",
    title: "UX Design Intern",
    company: "Apple",
    location: "Cupertino, CA",
    description: "Design products that enrich people's lives. Work on iOS, macOS, and hardware experiences.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://jobs.apple.com/en-us/search?team=internships-STDNT-INTRN",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Design",
    opportunity_type: "internship",
    match_score: 85,
    tags: ["Figma", "Sketch", "Prototyping", "User Research"],
    source: "direct",
  },
  {
    id: "google-ux-intern-2025",
    title: "UX Design Intern",
    company: "Google",
    location: "Mountain View, CA",
    description: "Design experiences used by billions. Work on Search, Maps, Chrome, and more.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://www.google.com/about/careers/applications/jobs/results/?q=ux%20intern",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Design",
    opportunity_type: "internship",
    match_score: 86,
    tags: ["Figma", "User Research", "Prototyping", "Design Systems"],
    source: "direct",
  },
  // Finance / Business Internships
  {
    id: "jpmorgan-tech-intern-2025",
    title: "Software Engineer Intern",
    company: "JPMorgan Chase",
    location: "San Francisco, CA",
    description: "Build technology for global finance. Work on trading systems, payments, and more.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://careers.jpmorgan.com/us/en/students/programs/software-engineer-summer",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 83,
    tags: ["Java", "Python", "Cloud", "Finance"],
    source: "direct",
  },
  {
    id: "goldman-swe-intern-2025",
    title: "Engineering Summer Analyst",
    company: "Goldman Sachs",
    location: "San Francisco, CA",
    description: "Build technology for global markets. Work on trading, risk, and platform engineering.",
    salary_min: 7500,
    salary_max: 9500,
    url: "https://www.goldmansachs.com/careers/students/programs/americas/summer-analyst-program.html",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 84,
    tags: ["Java", "Python", "Finance", "Distributed Systems"],
    source: "direct",
  },
  // More entry-level jobs
  {
    id: "amazon-sde-new-grad-2025",
    title: "Software Development Engineer - New Grad",
    company: "Amazon",
    location: "San Francisco, CA",
    description: "Start your career at Amazon. Build systems that power e-commerce and AWS.",
    salary_min: 145000,
    salary_max: 175000,
    url: "https://www.amazon.jobs/en/teams/internships-for-students",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "job",
    match_score: 91,
    tags: ["Java", "AWS", "Python", "Distributed Systems"],
    source: "direct",
  },
  {
    id: "microsoft-new-grad-2025",
    title: "Software Engineer - New Graduate",
    company: "Microsoft",
    location: "Mountain View, CA",
    description: "Empower every person and organization. Build products used by billions.",
    salary_min: 140000,
    salary_max: 170000,
    url: "https://careers.microsoft.com/students/us/en/usuniversityjobs",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "job",
    match_score: 89,
    tags: ["C#", "TypeScript", "Azure", "AI"],
    source: "direct",
  },
  {
    id: "netflix-new-grad-2025",
    title: "Software Engineer - New Grad",
    company: "Netflix",
    location: "Los Gatos, CA",
    description: "Entertain the world. Build streaming technology at scale.",
    salary_min: 160000,
    salary_max: 200000,
    url: "https://jobs.netflix.com/search?q=new%20grad",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "job",
    match_score: 88,
    tags: ["Java", "Python", "AWS", "Microservices"],
    source: "direct",
  },
  // Sacramento / Central Valley
  {
    id: "state-ca-analyst-2025",
    title: "IT Associate Analyst",
    company: "State of California",
    location: "Sacramento, CA",
    description: "Serve Californians through technology. Work on systems that support state government.",
    salary_min: 55000,
    salary_max: 75000,
    url: "https://www.calcareers.ca.gov/",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Government",
    opportunity_type: "job",
    match_score: 75,
    tags: ["Java", "SQL", "Government", "IT"],
    source: "direct",
  },
  {
    id: "uc-davis-health-swe-2025",
    title: "Software Developer - Entry Level",
    company: "UC Davis Health",
    location: "Sacramento, CA",
    description: "Build healthcare technology. Support patient care through innovative software.",
    salary_min: 65000,
    salary_max: 85000,
    url: "https://health.ucdavis.edu/careers/",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Healthcare",
    opportunity_type: "job",
    match_score: 76,
    tags: ["Java", "Healthcare", "SQL", "HIPAA"],
    source: "direct",
  },
  {
    id: "intel-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Intel",
    location: "Santa Clara, CA",
    description: "Shape the future of computing. Work on hardware and software that powers the world.",
    salary_min: 7000,
    salary_max: 9000,
    url: "https://jobs.intel.com/en/search-jobs?k=intern",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 85,
    tags: ["C++", "Python", "Hardware", "AI"],
    source: "direct",
  },
  {
    id: "cisco-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Cisco",
    location: "San Jose, CA",
    description: "Power an inclusive future for all. Build networking and collaboration technology.",
    salary_min: 6500,
    salary_max: 8500,
    url: "https://jobs.cisco.com/jobs/SearchJobs/intern",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 82,
    tags: ["Python", "Networking", "Cloud", "Security"],
    source: "direct",
  },
  {
    id: "vmware-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "VMware (Broadcom)",
    location: "Palo Alto, CA",
    description: "Build the multi-cloud future. Work on virtualization and cloud infrastructure.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://careers.vmware.com/",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 81,
    tags: ["Java", "Python", "Cloud", "Kubernetes"],
    source: "direct",
  },
  {
    id: "oracle-swe-intern-2025",
    title: "Software Engineer Intern - OCI",
    company: "Oracle",
    location: "Redwood City, CA",
    description: "Build next-generation cloud infrastructure. Work on Oracle Cloud Infrastructure.",
    salary_min: 6500,
    salary_max: 8500,
    url: "https://www.oracle.com/corporate/careers/students-grads/",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 80,
    tags: ["Java", "Cloud", "Kubernetes", "Linux"],
    source: "direct",
  },
  {
    id: "hp-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "HP Inc.",
    location: "Palo Alto, CA",
    description: "Create technology that makes life better. Work on printing and personal systems.",
    salary_min: 6000,
    salary_max: 7500,
    url: "https://jobs.hp.com/en-us/students-careers/",
    posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 77,
    tags: ["Python", "C++", "Firmware", "Cloud"],
    source: "direct",
  },
  {
    id: "juniper-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Juniper Networks",
    location: "Sunnyvale, CA",
    description: "Power connections that matter. Build networking technology for the AI era.",
    salary_min: 6500,
    salary_max: 8000,
    url: "https://www.juniper.net/us/en/company/culture/careers.html",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 79,
    tags: ["Python", "Networking", "Linux", "Cloud"],
    source: "direct",
  },
  {
    id: "palo-alto-networks-intern-2025",
    title: "Software Engineer Intern",
    company: "Palo Alto Networks",
    location: "Santa Clara, CA",
    description: "Protect the digital way of life. Build cybersecurity solutions.",
    salary_min: 7000,
    salary_max: 9000,
    url: "https://jobs.paloaltonetworks.com/en/students",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 86,
    tags: ["Python", "Security", "Cloud", "Go"],
    source: "direct",
  },
  {
    id: "crowdstrike-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "CrowdStrike",
    location: "Sunnyvale, CA",
    description: "Stop breaches. Build next-generation cybersecurity technology.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://www.crowdstrike.com/careers/university-recruiting/",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 87,
    tags: ["Go", "Python", "Security", "Cloud"],
    source: "direct",
  },
  {
    id: "zscaler-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Zscaler",
    location: "San Jose, CA",
    description: "Secure digital transformation. Build zero trust security solutions.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://www.zscaler.com/careers",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 84,
    tags: ["Java", "Python", "Security", "Cloud"],
    source: "direct",
  },
  {
    id: "okta-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Okta",
    location: "San Francisco, CA",
    description: "Free everyone to safely use any technology. Build identity and access management.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://www.okta.com/company/careers/",
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 85,
    tags: ["Java", "Go", "Security", "Identity"],
    source: "direct",
  },
  {
    id: "splunk-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Splunk (Cisco)",
    location: "San Francisco, CA",
    description: "Turn data into doing. Build observability and security platforms.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://www.splunk.com/en_us/careers.html",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 83,
    tags: ["Python", "Java", "Data", "Cloud"],
    source: "direct",
  },
  {
    id: "elastic-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Elastic",
    location: "Mountain View, CA",
    description: "Search and analyze data. Build the Elastic Stack used by thousands of companies.",
    salary_min: 7000,
    salary_max: 8500,
    url: "https://www.elastic.co/about/careers/",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 82,
    tags: ["Java", "Go", "Search", "Cloud"],
    source: "direct",
  },
  {
    id: "mongodb-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "MongoDB",
    location: "San Francisco, CA",
    description: "Build the developer data platform. Work on the world's most popular document database.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://www.mongodb.com/company/careers",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 86,
    tags: ["C++", "Go", "Databases", "Distributed Systems"],
    source: "direct",
  },
  {
    id: "confluent-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Confluent",
    location: "Mountain View, CA",
    description: "Set data in motion. Build the data streaming platform based on Apache Kafka.",
    salary_min: 7500,
    salary_max: 9500,
    url: "https://www.confluent.io/careers/",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 87,
    tags: ["Java", "Go", "Kafka", "Distributed Systems"],
    source: "direct",
  },
  {
    id: "hashicorp-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "HashiCorp",
    location: "San Francisco, CA",
    description: "Enable the cloud operating model. Build infrastructure automation tools.",
    salary_min: 7500,
    salary_max: 9000,
    url: "https://www.hashicorp.com/careers",
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 88,
    tags: ["Go", "Terraform", "Cloud", "DevOps"],
    source: "direct",
  },
  {
    id: "cloudflare-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Cloudflare",
    location: "San Francisco, CA",
    description: "Help build a better internet. Work on the global network that powers millions of sites.",
    salary_min: 8000,
    salary_max: 9500,
    url: "https://www.cloudflare.com/careers/",
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 89,
    tags: ["Go", "Rust", "Networking", "Distributed Systems"],
    source: "direct",
  },
  {
    id: "vercel-swe-intern-2025",
    title: "Software Engineer Intern",
    company: "Vercel",
    location: "San Francisco, CA",
    description: "Develop the web. Build the frontend cloud platform for developers.",
    salary_min: 8000,
    salary_max: 10000,
    url: "https://vercel.com/careers",
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 90,
    tags: ["TypeScript", "React", "Next.js", "Edge"],
    source: "direct",
  },
  {
    id: "supabase-swe-intern-2025",
    title: "Software Engineering Intern",
    company: "Supabase",
    location: "San Francisco, CA",
    description: "Build the open source Firebase alternative. Create database infrastructure for developers.",
    salary_min: 7500,
    salary_max: 9500,
    url: "https://supabase.com/careers",
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: "Engineering",
    opportunity_type: "internship",
    match_score: 88,
    tags: ["TypeScript", "PostgreSQL", "Elixir", "Go"],
    source: "direct",
  },
];

function calculateMatchScore(opportunity: Opportunity, userSkills: string[] = []): number {
  let score = opportunity.match_score;

  // Boost score based on user skills matching tags
  userSkills.forEach((skill) => {
    if (opportunity.tags.some((tag) => tag.toLowerCase() === skill.toLowerCase())) {
      score = Math.min(score + 3, 99);
    }
  });

  return score;
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const category = searchParams.get("category") || "all";
  const userSkillsParam = searchParams.get("skills") || "";
  const userSkills = userSkillsParam ? userSkillsParam.split(",") : [];
  const userSearch = searchParams.get("search") || "";

  // Filter opportunities by category
  let opportunities = [...curatedOpportunities];

  if (category === "internship" || category === "internships") {
    opportunities = opportunities.filter((o) => o.opportunity_type === "internship");
  } else if (category === "job" || category === "jobs") {
    opportunities = opportunities.filter((o) => o.opportunity_type === "job");
  }

  // Recalculate match scores based on user skills
  opportunities = opportunities.map((o) => ({
    ...o,
    match_score: calculateMatchScore(o, userSkills),
  }));

  // Sort by match score
  opportunities.sort((a, b) => b.match_score - a.match_score);

  return NextResponse.json({
    opportunities,
    total: opportunities.length,
  });
}
